# ===============================
# PERFIL PRODUCCION
# ===============================

batch.chunk-size=100
batch.skip-limit=50
batch.retry-limit=5

batch.executor.core-pool-size=5
batch.executor.max-pool-size=10
batch.executor.queue-capacity=100

batch.backoff.initial-interval=1000
batch.backoff.multiplier=2.0
batch.backoff.max-interval=10000