# ===============================
# PERFIL DESARROLLO
# ===============================

batch.chunk-size=5
batch.skip-limit=20
batch.retry-limit=3

batch.executor.core-pool-size=3
batch.executor.max-pool-size=3
batch.executor.queue-capacity=25

batch.backoff.initial-interval=1000
batch.backoff.multiplier=2.0
batch.backoff.max-interval=10000