spring.application.name=bffatm

server.port=8093

services.cuentas.url=http://localhost:8081
services.intereses.url=http://localhost:8082

# ================================
# JWT USUARIO - ATM -> BFF
# ================================

jwt.secret=clave-jwt-bff-atm-semana4-2026-super-secreta-123456789

jwt.expiration=3600000


# ================================
# SERVICE TOKEN - BFF -> MICROS
# ================================

jwt.service-secret=clave-compartida-bff-semana4-2026-1234567890

jwt.service-expiration=300000

# ================================
# HTTPS / SSL
# ================================

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=semana4
server.ssl.key-alias=https_certs